2020/budon_python/news/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', NewsListMainView.as_view(), name='main'),
    path('news_list/', NewsListView.as_view(), name='news_list'),
    path('news_create/', NewsCreateView.as_view(), name='news_create'),
    path('news_detail/<int:pk>', NewsDetailView.as_view(), name='news_detail'),
    path('news_update/<int:pk>', NewsUpdateView.as_view(), name='news_update'),
    path('news_delete/<int:pk>', NewsDeleteView.as_view(), name='news_delete'),
]

2020/budon_python/news/models.py
from django.db import models
from django.urls import reverse


class News(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse('news:news_detail', args=[str(self.id)])

2020/budon_python/news/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


# Create your views here.
from news.models import News


class NewsCreateView(LoginRequiredMixin, CreateView):
    login_url = settings.LOGIN_URL
    template_name = 'news/news_create.html'
    model = News
    fields = ['title', 'content']
    success_url = reverse_lazy('news_list')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.pk
        return super().form_valid(form)


class NewsListMainView(ListView):
    template_name = 'news/main.html'
    model = News
    paginate_by = 3


class NewsListView(ListView):
    template_name = 'news/news_list.html'
    model = News
    paginate_by = 8


class NewsDetailView(DetailView):
    model = News


class NewsUpdateView(UpdateView):
    model = News
    fields = ['title', 'content']
    template_name_suffix = '_update'
    success_url = reverse_lazy('news_list')


class NewsDeleteView(DeleteView):
    model = News
    success_url = reverse_lazy('news_list')

2020/budon_python/news/templates/news/main.html
{% extends 'base_main.html' %}

{% block content %}
<a class="ico-more" href="{% url 'news_list' %}">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"/>
    </svg>
    <span>more</span>
</a>
<div class="list-card">
    {% for news in object_list %}
    <a class="list" href="{% url 'news_detail' pk=news.id %}">
        <h3 class="list-title">{{ news.title }}</h3>
        <div class="content">{{ news.content }}</div>
    </a>
    {% endfor %}
</div>

{% endblock %}

2020/budon_python/news/templates/news/news_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
<form class="confirm_delete" action="" method="post">
    {% csrf_token %}
    <div class="alert alert-danger">Do you want to delete Bookmark "{{object}}"?</div>
    <input type="submit" value="Delete" class="btn btn-danger">
</form>
{% endblock %}

2020/budon_python/news/templates/news/news_create.html
{% extends 'base.html' %}

{% block title %}News 올리기{% endblock %}

{% block content %}
<section id="news">
    <h2 class="title" data-count="03">News</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class="input-container">
            <label for="id_title">Title:</label>
            <input type="text" name="title" maxlength="200" required="" id="id_title">
        </div>
        <div class="input-container">
            <label for="id_content">Content:</label>
            <textarea name="content" cols="40" rows="10" required="" id="id_content"></textarea>
        </div>
        <input type="submit" value="Add" class="btn btn-info btn-sm">
    </form>
</section>
{% endblock %}

2020/budon_python/news/templates/news/news_detail.html
{% extends 'base.html' %}

{% block title %}Detail{% endblock %}

{% block content %}
<section id="news">
    <h2 class="title" data-count="03">News</h2>
    <div class="list detail">
        <h3 class="list-title">{{ news.title }}</h3>
        <div class="content">{{ news.content|linebreaks }}</div>
    </div>
    <div class="button-container">
        {% if user.is_active %}
        <button onclick="location.href='{% url 'news_update' pk=news.id %}'">수정</button>
        <button onclick="location.href='{% url 'news_delete' pk=news.id %}'">삭제</button>

        {% endif %}
        <button onclick="location.href='{% url 'news_list' %}'">목록으로</button>
    </div>
</section>
{% endblock %}}

2020/budon_python/news/templates/news/news_list.html
{% extends 'base.html' %}
{% block title %} 공지사항 {% endblock %}

{% block content %}
<section id="news">
    <h2 class="title" data-count="03">News</h2>
    <a class="ico-create" href="{% url 'news_create' %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"/>
        </svg>
    </a>
    {% for news in object_list %}
    <a class="list" href="{% url 'news_detail' pk=news.id %}">
        <div class="list-title">
            <span>{{ news.title }}</span>
            <span class="username">{{ news.author.username }}</span>
        </div>
    </a>
    {% endfor %}
    {% block pagination %}
    {% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="{% url 'news_list' %}?page={{ page_obj.previous_page_number }}" tabindex="-1"
               class="page-link">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a href="#" class="page-link" tabindex="-1">Previous</a>
        </li>
        {% endif %}

        {% for object in page_obj.paginator.page_range %}
        <li class="page-item {% if page_obj.number == forloop.counter %} disabled{% endif %}">
            <a href="{{ request.path }}?page={{ forloop.counter }}"
               class="page-link">{{ forloop.counter }}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a href="{% url 'news_list' %}?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a href="#" class="page-link">Next</a>
        </li>
        {% endif %}
    </ul>
    {% endif %}
    {% endblock %}
</section>
{% endblock %}

2020/budon_python/news/templates/news/news_update.html
{% extends 'base.html' %}

{% block title %}News 올리기{% endblock %}

{% block content %}
<section id="news">
    <h2 class="title" data-count="03">News</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-container">
            <label for="id_title">Title:</label>
            <input type="text" name="title" maxlength="200" required="" id="id_title" value="{{ form.title.value }}">
        </div>
        <div class="input-container">
            <label for="id_content">Content:</label>
            <textarea name="content" cols="40" rows="10" required="" id="id_content">{{ form.content.value }}</textarea>
        </div>
        <input type="submit" value="Add" class="btn btn-info btn-sm">
    </form>
</section>
{% endblock %}